export const DEBOUNCE_DELAYS = {
	TEXT_INPUT: 300,
	SEARCH: 500,
	API_CALLS: 1000,
	RESIZE: 100,
} as const;

export const PERFORMANCE_THRESHOLDS = {
	LARGE_LIST_SIZE: 100,
	TEXT_LENGTH_WARNING: 2000,
	MAX_RENDERED_ITEMS: 50,
} as const;

export const MEMORY_LIMITS = {
	MAX_CACHED_COMPONENTS: 10,
	MAX_STORED_ERRORS: 10,
	CLEANUP_INTERVAL: 300000,
} as const;
